model_list:
  - model_name: deepseek-v4-flash
    litellm_params:
      model: openai/deepseek-v4-flash-0731
      api_base: os.environ/WEBUI_BASE_URL
      api_key: os.environ/WEBUI_API_KEY
      use_chat_completions_api: true

  - model_name: deepseek-v4-pro
    litellm_params:
      model: openai/deepseek-v4-pro
      api_base: os.environ/WEBUI_BASE_URL
      api_key: os.environ/WEBUI_API_KEY
      use_chat_completions_api: true

general_settings:
  enable_responses_api_to_chat_completions_translation: true